package main

import "fmt"

func handleError(err error) {
	fmt.Errorf("err: ", err)
}